#+BEGIN_COMMENT
.. title: Fibonacci Number Again
.. slug: fibonacci-number-again
.. date: 2018-06-27 15:52:25 UTC-07:00
.. tags: problems algorithms fibonacci
.. category: problems
.. link: 
.. description: Calculate Fibonacci number /n/ modulo m.
.. type: text
#+END_COMMENT

#+BEGIN_SRC ipython :session fibonacci :results none
from algorithmic_toolbox.implementations import fibonacci
#+END_SRC

* Introduction
  In this problem we will calculate $F_n \mod m$ where $n$ can be very large (up to $10^{18}$). To see how to do this look at some output for modulus operations.

#+BEGIN_SRC ipython :session fibonacci :results output
for number in range(15):
    print(fibonacci(number) % 2, end=', ')
#+END_SRC

#+RESULTS:
: 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 

You can see that the output repeats in cycles of three.

#+BEGIN_SRC ipython :session fibonacci :results output
cycle = [0, 1, 1]
for number in range(15):
    print(cycle[number % 3], end=',')
#+END_SRC

#+RESULTS:
: 0,1,1,0,1,1,0,1,1,0,1,1,0,1,1,

So if you know the cycle, you don't need to calculate the fibonacci number. What about mod 3?

#+BEGIN_SRC ipython :session fibonacci :results output
for number in range(16):
    print(fibonacci(number) % 3, end=',')
#+END_SRC

#+RESULTS:
: 0,1,1,2,0,2,2,1,0,1,1,2,0,2,2,1,

It looks like it repeats every eight numbers. In general, the fact that the modulus of fibonacci numbers is periodic was is a known feature of them. Each period is known as a [[https://en.wikipedia.org/wiki/Pisano_period][Pisano period]] (Pisano was the real last name of the man known as Fibonacci).

* Problem Description

|               | Description                                                                                  |
|---------------+----------------------------------------------------------------------------------------------|
| *Task*        | Given two integers $n$ and $m$, output $F_n \mod m$ (the remainder of $F_n$ divided by $m$). |
| *Input*       | Two integers $n$ and $m$ on the same line separated by a space.                              |
| *Constraints* | $1 \le n \le 10^{18}, 2 \le m \le 10^3$                                                      |
| *Output*      | $F_n \mod m$                                                                                 |

* Samples

| Input          | Output |                           |
|----------------+--------+---------------------------|
| 239 1000       |    161 | $F_{239} \mod 1000        |
| 2816213588 239 |    151 | $F_{2816213588} \mod 239$ |

